<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<AssemblyName>TimeMarkEdit</AssemblyName>
		<OutputType>Library</OutputType>

		<LangVersion>10.0</LangVersion>
		<Nullable>enable</Nullable>

		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
		<AssemblyVersion>1.0.8.0</AssemblyVersion>
		<FileVersion>1.0.8.0</FileVersion>
		<RootNamespace>TimeMarkEdit</RootNamespace>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Configuration\TimeMarkEdit.html">
			<LogicalName>TimeMarkEdit.Configuration.TimeMarkEdit.html</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Configuration\TimeMarkEditManager.js">
			<LogicalName>TimeMarkEdit.Configuration.TimeMarkEditManager.js</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Configuration\TimeMarkEditSummary.html">
			<LogicalName>TimeMarkEdit.Configuration.TimeMarkEditSummary.html</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Configuration\TimeMarkEditSummaryManager.js">
			<LogicalName>TimeMarkEdit.Configuration.TimeMarkEditSummaryManager.js</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Configuration\TimeMarkEditDetections.html">
			<LogicalName>TimeMarkEdit.Configuration.TimeMarkEditDetections.html</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Configuration\TimeMarkEditDetectionsManager.js">
			<LogicalName>TimeMarkEdit.Configuration.TimeMarkEditDetectionsManager.js</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Configuration\TimeMarkEditVideoPlayer.js">
			<LogicalName>TimeMarkEdit.Configuration.TimeMarkEditVideoPlayer.js</LogicalName>
		</EmbeddedResource>
		<EmbeddedResource Include="Images\logo.jpg" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MediaBrowser.Server.Core" Version="4.9.1.90">
			<PrivateAssets>all</PrivateAssets>
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
		<PackageReference Include="ServiceStack" Version="8.2.2">
			<PrivateAssets>all</PrivateAssets>
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
